Ide coercion intentions (#502)
* default to `Nothing` in IR if a type arg is unbound in a resolved proof

* Fix previous merge

* CI: improve check output

* Fix patch for next version 1.3.70

* build Prelude (#433)

* add prelude

* Update build.gradle

* Refinement first steps. Validating runtime predicates at compile time

* Testing plugin: consider packages

* Refinement proofs helper functions reorg

* Fixes ide in type-proofs (#461)

* Hide/show slack channel text box (#426)

* Adds github stars button, github modal and includes kotlin slack channel link

* Adds slack channel toogle button

* Fix patch for 1.3.70: getting extensionPoints (#427)

* Remove unnecessary z-index property (#428)

* Sync versions for Kotlin, Kotlin IDEA plugin and Intellij IDEA (#429)

Co-authored-by: Raúl Raja Martínez <raulraja@gmail.com>

* fix to not export package probably caused for choose runtime plugin (#430)

* fix 404 for ide testing (#431)

* Gradle Plugin: add compiler-plugin dependency from the plugin (#422)

Co-authored-by: Imran Settuba <46971368+i-walker@users.noreply.github.com>

* Deprecations and Improvements on Intentions (#388)

* init

* cleanUp

* clean Up

* added docs

* mergeable LineMarkers & further Rendering options (#434)

* improve

* done

* clickAction

* cleaUp

* clickAction

* Tool windows and minor fixes (#417)

* prog

* cleanUp

* remove

* ready for review

* done

* clean Up

* decomposed functions

* clean Up

Co-authored-by: Raúl Raja Martínez <raulraja@gmail.com>

* Sync versions for Kotlin, Kotlin IDEA plugin and Intellij IDEA (#441)

Co-authored-by: Raúl Raja Martínez <raulraja@gmail.com>

* Revert "Gradle Plugin: add compiler-plugin dependency from the plugin" (#442)

* Revert "Gradle Plugin: add compiler-plugin dependency from the plugin (#422)"

This reverts commit 9011f3f7fa75aed8b40397228daf57db93191b46.

* Build check: generic EAP or DEV version

* GotoRelatedProvider and the LineMarker version (#435)

* init

* LineMarker version

* clear

* clean Up

* cleanUp

* cleanUp (#443)

* remove QuickFixSyntax (#436)

* quickfix init

* cleanUp

* clean Up

* Update gradle.properties (#452)

* Remove `@sample` from KDoc for Hello World IDE plugin (#451)

It was causing a confusing doc page to be generated, with all the
information shown twice.

* Removes component (#455)

* done

* naive impl

* remove naive wrapper

* cleanup

* fix

* fix

Co-authored-by: AntonioMateoGomez <antonio.mateo@47deg.com>
Co-authored-by: Rachel M. Carmena <rachelcarmena@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Raúl Raja Martínez <raulraja@gmail.com>
Co-authored-by: matias lev <39838885+matiaslev@users.noreply.github.com>
Co-authored-by: Chris Birchall <chris.birchall@gmail.com>

* Move type refinements to post analysis before IR to support complex predicates like arrays

* given identity tests, some unfinished docs and beginning of derivation

* cleanUp

* IDE fixes

* Evaluate refined predicates without the script engine manager

* REPL showing issue on IDEA

* More conflicts

* Progress with type refinement error reporting

* Adjust proofs to new API

* Wire the irModuleFragment not the files

* Merge master into sv-test-proofs

* TypeClassesTest working

* Refinements highlighting working in the IDE

* Progress toward refinement in the IDE

* Update INTELLIJ_GRADLE_PLUGIN_VERSION=0.4.17
Make explicit coercion to be implicit (wip)

* Filter calls and check for subtype

* Fix for java.lang.NoClassDefFoundError: kotlin/internal/ir/Intrinsic, thanks to @ShikaSD https://kotlinlang.slack.com/archives/C7L3JB43G/p1584971604067800

* All compiler-plugin tests passing

* Nits

* WIP Latest develop

* Move coercion work to single file

* nit: add logs

* Add case for KtDotQualifiedExpression

* Nits

* Change on ProofResolution to grab the coercion property
Change the module assigned to the CompilerContext (but still missing the proofs about TwitterHandle)

* Make explicit coercion to be implicit

* Moved refinement highlighter out of plugins.

* Refinement line markers

* WIP

* Fixes deadlock by moving initialization of proofs in IDE to when the resolution facade is created for each highlighting

* WIP to add coercion line marker

* Highlight coercion happening working (switched subtype and supertype)

* Split coercion intentions

* Nits and moves.

* replace Project Component in Proofs with ProjectLifecycleListener

* Update coercion line marker message with the proof applied (missing adding the actual link to the proof)

* WIP

* Draft to check for Coercion functions (#501)

* Make explicit coercion to be implicit (wip)
* Make explicit coercion to be implicit (wip)

* Make implicit call to be explicit for KtProperty

* Fix ex/implicit param types functions

* Make implicit call to be explicit for KtProperty

* Some rework, made KtCallElement work

* Suppress type mismatch if proof allows coercion

* Fix prelude proofs and tests related to coercion functions

* Add explicit conversion for call elements

* Replace ktpsiFactory in favor of ElementScope (missing add imports)

* Use listOrNull to simplify the code

Add import from proof on conversion

* fix

* minor improvements

* convenience function sequence

* minor improvement

* WIP migrate intention to applicable inspection

* merged and cleaned up #464

* clean up

* hot fix regarding https://github.com/arrow-kt/arrow-meta/issues/514

* fix regarding #513

* Simplify display of Union and Tuple types by creation of FoldingBuilder (#506)

* Adding extensionPhase for FoldingBuilder syntax

* Created placeholder addUnionFoldingBuilder

* Register UnionFoldingBuilder through plugin.xml

* Move UnionFoldingBuilder into plugins

* Trying to iterate through the Psi's

* polishing buildFoldRegions to iterate through the KtTypeReference

* Add implementation of getPlaceholderText to display the right mask

* Folding builder for tuples

* Fix imports

* Merge sv-test-proofs into this

* Add folding builder for Kind<F, A> ~> F<A>

* done

Co-authored-by: i-walker <46971368+i-walker@users.noreply.github.com>

* disable IntentionSyntax

* disable Intensions until #502 is enabled

* improved LM performance

* speed up LM

* enable RelatedItemLineMarker

* Fixed substitution of type args over kinded values

* Some cleanup

* Fix inspection imports

* Naming nit

* Add proofs path

* kotlin type API from #114

* Temporarily disable extra annotators and line markers for the tests to be executed

Added very basic test to investigate how to test intentions (WIP)

* Patch for ide-refactor in type proofs (#522)

* disable IntentionSyntax (#515)

* introduce CliPlugin

* introduce IdePlugin and refactor ide-plugin

* add logs

* sync with proofs branch (#517)

* patched for proofs

* remove CompilerContext.files

* deprecating HKT Tests in the Ide, as the new encoding is in the making

* clean up after merge

* inspection test dsl

* editorActions

* new test encoding

* init

* fix tests

* type inference

* test

* cleanUp

* stabilises member resolution (#532)

* works not

* works

* List kinded ad-hoc test changes

* progress

* A better ADT for proofs and start to support given canonical value injection

* Generalized Proofs member scope to all callable members not just extension proofs

* given, coercion, refinement and extension

* Behold Coherent Given implicits

* hijack KotlinCacheService through ApplicationSyntax

* All compiler-plugin tests passing for new proof shapes including given implicits

* given implicits

* Adapt patch for 1.3.7x: compilation errors

* IDE improvements

* Adapt patch for 1.4x

* CI: don't check next version until 1.3.7x failures are solved

* Doc: solve Ank failures for compiler-plugin

* Suppress thread death error, which is caused when the Kotlin Compiler script engine closes a background thread. (#539)

* add Docs to ScriptEngine

* register suppressed Diagnostics in the Cli

* Fix code snippets for idea-plugin

* Update Arrow to 0.10.5 (Arrow Ank included)

* Fix doc generation and validation

* Revert to Arrow 0.10.4-SNAPSHOT and keep 0.10.5 for Arrow Ank Gradle Plugin

* Fix IDE test schema example

* Disable until it's fixed with another PR

* Disable Ank for commented example

* Remove duplicated import

* Refactor to register foldings through the ExtensionProvider (#521)

* Refactor to register foldings through the ExtensionProvider

* Address comments from draft

* Add util to resolve kotlinType for a KtTypeReference,
Refactor to check for Kind type instead of Kind string
Apply folding over the children too

* Refactor to check for Union and Tuple type instead of Union or Tuple strings

* Merge sv-test-proofs into this

* Refactor api for FoldingSyntax.foldingBuilder to work with ktElements instead of nodes

* Group code foldings for Unions, Tuples and Kinds

* Improve FoldingSyntax
Refactor and Add new dsl (wip - need to add EventAction)

* Refactor folding Kind and Union to follow the new dsl

* Add extension for automatically collapse regions (wip)

* WIP - add caret listener for fold back the regions

* Add dsl to add FileEditorManagerListener through the Topic
Add caret listener within foldingFileEditor

* Group together all folding stuff
Polish isCollapsedByDefault to match only with the types we want

* Add Noops

* Add EditorSyntax and address PR comments

* Address some PR comments

* Address PR comments

* Address PR comments

* Address PR comments

* Address PR comments

* Remove missing function, rename function to avoid conflict

* Disable Ank for commented example

* Remove missing function

* Update branch

* Fix println

* First draft about docs/build.gradle

* Establish a 1:1 mapping for CompilerContext in CLI and IDE

* fix patch for ide

* Refactor + add buildMetaDoc Gradle task

* Refactor

* Refactor

* Change log

* Revert "Change log"

This reverts commit 6a7a49117894f3c2a61c23bf632a747a3c3e63c4.

* Revert "Refactor"

This reverts commit bf24268d27b791c89e71349fb9a4a1b58040c0b8.

* Revert "Refactor"

This reverts commit fa0c6278a870587cd28a62390af350bb8397f264.

* Revert "Refactor + add buildMetaDoc Gradle task"

This reverts commit f56da117257d5925467ba7a79a063f97ee59ff62.

* Add buildMetaDoc task (#550)

* Relocate Ank plugin (#552)

* Upgrade to Arrow 0.10.5 (#553)

* Fix patch for 1.3.7x

* Fix: add projectDir

* Fix path

* Folding builder test for Unions and Tuples (#548)

* Skeleton for testing folding builders

* Folding builder test for Union and Tuple (wip)

* Disable folding builder for Kind

* Add filter to avoid collapsing imports or other regions (only focus on our types)

* Address use case when Union type is nullable

* Update union foldString to address nullables

* Add file to myFixture so testing code from definitions are in different files (test returns right result.. but its not being disposed)

* fix patch

* Fix: remove patch in patch

* Add limit of types when union is folded and truncate the rest (#558)

Noticed RefinementTests is failling.. might be a flaky test

* Update branch and change explicit and implicit coercion on how to get the compiler context

* Fix typeclass syntax navigation (#562)

* Preserves source element every time we create a descriptor copy.

* Removes commented code.

* refine Ank Docs

* refine FoldingTest

* doc fix

* Move explicit and implicit coercions to typeProofsIde plugin

* Fix implicit participating types

* Minor change

* cleanUp

* Fix line marker for both coercions and some refactor

* Fix patch for 1.3.7x

* Replaced KtCallElement for KtValueArgument so we check value arguments individually

* Show coercion line marker only for implicit ones

* Fix coercion line markers split into two: properties and valueArguments

* Update RefinementTests.kt

* Ignore ImplicitcoercionTest.kt

* Add addLineMarkerProviderM dsl just for KtValueArgument's or we can merge the same line marker icon into only one

* Line marker coercion tests (#507)

* Test to check if coercion line marker shows up

* Enable only coerceProofLineMarker

* Add Proof and Refined types

* Add temporary prelude project to get the proofs and add file twitterHandle declaration to myFixture

* Merge sv-test-proofs into this

* Update test after all changes

* Add prelude definition

* Fix implicit coercion focusing on the leaf KtProperty
Test working

* Fix test coercion line markers (wip: ktvalueArgument)

* Ignore test for now

* Update RefinementTests.kt

* Update tests (still failing because LineMarker is supposed to be registered for leaf elements only)

* Update tests (work for leafs but and icons are visually merged.. but not on the tests..)

* CoercionTest3 should return 1

* Refactor on coercion inspections so we can move on when doing the tests
Explicit coercion inspection being detected on tests

* Tests for the highlighting part of the inspection for explicit and implicit coercions

* Inspection highlights and fixes tested for implicit and explicit coercions

* Remove specific dsl for KtValueArgument and re-use existent one

* Added tests for highlight and fix for coercions happening within the arguments

* Tested that desctructuring and named arguments work

* Disabling inspection to make an explicit coercion to be implicit if parent expression is a KtSafeQualifiedExpression so we avoid a bad definition of the expression (if we would be applying that fix)

* Change indentation

* Rename coercionLineMarker to reflect is the call site one instead of the definition of the proof
and `Composite` coercion inspections

* Remove check if areTypesCoerced when making the coercion explicit since that should be the case already (done by isApplicable)

* Rename explicit / implicit coercion inspections

* Merge highlight and fix inspection

* Add specific extension for adding line markers targeting psiElements that are not leafs

* Split explicit coercions into properties and arguments and some refactor

* Inspection was not enabled by default because of the `defaultFixText` (too long)

* Remove typeProofsCli from ProofsIdePlugin

* Some refactor

* Some refactor

* Remove some duplicate test code

* Some refactor

* Some more refactor

* Some more refactor

* Some more refactor

* reorg

* replace

* Some more refactor: collectAndApplyInspection

* fix

* Adding missing types

* refined

* Adding missing types

* refine

* There are 2 explicit coercions and apply fix for the first one

* RefinementTests has changed

Co-authored-by: Rachel M. Carmena <rachelcarmena@users.noreply.github.com>
Co-authored-by: Raul Raja <raulraja@gmail.com>
Co-authored-by: Imran Settuba <46971368+i-walker@users.noreply.github.com>
Co-authored-by: AntonioMateoGomez <antonio.mateo@47deg.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: matias lev <39838885+matiaslev@users.noreply.github.com>
Co-authored-by: Chris Birchall <chris.birchall@gmail.com>
Co-authored-by: danimontoya <daniel.montoya@47deg.com>
Co-authored-by: danieh <danimontoya_86@hotmail.com>
Co-authored-by: J. Ansorg <github@joachim-ansorg.de>
Co-authored-by: Jorge Castillo <jorge.castillo.prz@gmail.com>